### ISSUE TITLE
Immersive Engineering version 5.0.6-141 (new release) is incompatable with lattest version of Immersive Petrolium

### ISSUE THREAD

**Issue by Shibva** [TwistedGate/ImmersivePetroleum#72]
### Before reporting:
Please use the search function to make sure an issue hasn't been reported already. This avoids duplicates.  
Also, please give this issue a descriptive name that contains the game version in the title, eg.: "[1.16] Distillation Tower Interaction Crash"

### Description of the issue
when loading up the game after updating IE to 5.0.6-141, the game ran into a registry error doing initiation
### Versions and Modlist
irrelivent as it was stated in the title of this report and in the description of the issue
### Crash Log
Excript of the error 
```ime: 12/20/21 5:46 PM
Description: Mod loading error has occurred

java.lang.Exception: Mod Loading has failed
	at net.minecraftforge.fml.CrashReportExtender.dumpModLoadingCrashReport(CrashReportExtender.java:85) [?:?] {re:classloading}
	at net.minecraftforge.fml.client.ClientModLoader.completeModLoading(ClientModLoader.java:188) [?:?] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.lambda$null$1(Minecraft.java:508) [?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:randompatches.mixins.json:client.MinecraftMixin,pl:mixin:APP:betterendforge.mixins.json:MinecraftMixin,pl:mixin:APP:abnormals_core.mixins.json:client.MinecraftMixin,pl:mixin:APP:immersiveengineering.mixins.json:accessors.client.MinecraftAccess,pl:mixin:APP:flywheel.mixins.json:ShaderCloseMixin,pl:mixin:APP:performant.mixins.json:MinecraftMixin,pl:mixin:APP:create.mixins.json:WindowResizeMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft$$Lambda$18369/135940264.run(Unknown Source) [?:?] {}
	at net.minecraft.util.Util.func_215077_a(Util.java:430) [?:?] {re:classloading,xf:OptiFine:default,re:mixin,xf:OptiFine:default}
	at net.minecraft.client.Minecraft.lambda$new$2(Minecraft.java:504) [?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:randompatches.mixins.json:client.MinecraftMixin,pl:mixin:APP:betterendforge.mixins.json:MinecraftMixin,pl:mixin:APP:abnormals_core.mixins.json:client.MinecraftMixin,pl:mixin:APP:immersiveengineering.mixins.json:accessors.client.MinecraftAccess,pl:mixin:APP:flywheel.mixins.json:ShaderCloseMixin,pl:mixin:APP:performant.mixins.json:MinecraftMixin,pl:mixin:APP:create.mixins.json:WindowResizeMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft$$Lambda$18070/464277949.accept(Unknown Source) [?:?] {}
	at net.minecraft.client.gui.ResourceLoadProgressGui.func_230430_a_(ResourceLoadProgressGui.java:172) [?:?] {re:classloading,xf:OptiFine:default}
	at net.minecraft.client.renderer.GameRenderer.func_195458_a(GameRenderer.java:802) [?:?] {re:mixin,pl:accesstransformer:B,xf:OptiFine:default,xf:fml:astralsorcery:reach_set_client_renderer,re:classloading,pl:accesstransformer:B,xf:OptiFine:default,xf:fml:astralsorcery:reach_set_client_renderer,pl:mixin:APP:flywheel.mixins.json:StoreProjectionMatrixMixin,pl:mixin:APP:flickerfix.mixins.json:MixinGameRenderer,pl:mixin:A}
	at net.minecraft.client.Minecraft.func_195542_b(Minecraft.java:977) [?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:randompatches.mixins.json:client.MinecraftMixin,pl:mixin:APP:betterendforge.mixins.json:MinecraftMixin,pl:mixin:APP:abnormals_core.mixins.json:client.MinecraftMixin,pl:mixin:APP:immersiveengineering.mixins.json:accessors.client.MinecraftAccess,pl:mixin:APP:flywheel.mixins.json:ShaderCloseMixin,pl:mixin:APP:performant.mixins.json:MinecraftMixin,pl:mixin:APP:create.mixins.json:WindowResizeMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:607) [?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:randompatches.mixins.json:client.MinecraftMixin,pl:mixin:APP:betterendforge.mixins.json:MinecraftMixin,pl:mixin:APP:abnormals_core.mixins.json:client.MinecraftMixin,pl:mixin:APP:immersiveengineering.mixins.json:accessors.client.MinecraftAccess,pl:mixin:APP:flywheel.mixins.json:ShaderCloseMixin,pl:mixin:APP:performant.mixins.json:MinecraftMixin,pl:mixin:APP:create.mixins.json:WindowResizeMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.main.Main.main(Main.java:184) [?:?] {re:classloading,pl:runtimedistcleaner:A}
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_51] {}
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_51] {}
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_51] {}
	at java.lang.reflect.Method.invoke(Method.java:497) ~[?:1.8.0_51] {}
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider.lambda$launchService$0(FMLClientLaunchProvider.java:51) [forge-1.16.5-36.2.22.jar:36.2] {}
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider$$Lambda$496/10380027.call(Unknown Source) [forge-1.16.5-36.2.22.jar:36.2] {}
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37) [modlauncher-8.0.9.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:54) [modlauncher-8.0.9.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:72) [modlauncher-8.0.9.jar:?] {}
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:82) [modlauncher-8.0.9.jar:?] {re:classloading}
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:66) [modlauncher-8.0.9.jar:?] {re:classloading}


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at java.lang.ClassLoader.defineClass1(Native Method) ~[?:1.8.0_51] {}
-- MOD immersivepetroleum --
Details:
	Mod File: ImmersivePetroleum-1.16.5-3.3.0-8.jar
	Failure message: Immersive Petroleum (immersivepetroleum) has failed to load correctly
		java.lang.VerifyError: class flaxbeard.immersivepetroleum.common.blocks.tileentities.DistillationTowerTileEntity overrides final method shouldRenderAsActive.()Z
	Mod Version: 3.3.0-8
	Mod Issue URL: https://github.com/Flaxbeard/ImmersivePetroleum/issues
	Exception message: java.lang.VerifyError: class flaxbeard.immersivepetroleum.common.blocks.tileentities.DistillationTowerTileEntity overrides final method shouldRenderAsActive.()Z
Stacktrace:
	at java.lang.ClassLoader.defineClass1(Native Method) ~[?:1.8.0_51] {}
	at java.lang.ClassLoader.defineClass(ClassLoader.java:760) ~[?:1.8.0_51] {}
	at cpw.mods.modlauncher.TransformingClassLoader.loadClass(TransformingClassLoader.java:138) ~[modlauncher-8.0.9.jar:?] {re:classloading}
	at cpw.mods.modlauncher.TransformingClassLoader.loadClass(TransformingClassLoader.java:98) ~[modlauncher-8.0.9.jar:?] {re:classloading}
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[?:1.8.0_51] {}
	at java.lang.Class.forName0(Native Method) ~[?:1.8.0_51] {}
	at java.lang.Class.forName(Class.java:348) ~[?:1.8.0_51] {}
	at sun.reflect.generics.factory.CoreReflectionFactory.makeNamedType(CoreReflectionFactory.java:114) ~[?:1.8.0_51] {}
	at sun.reflect.generics.visitor.Reifier.visitClassTypeSignature(Reifier.java:125) ~[?:1.8.0_51] {}
	at sun.reflect.generics.tree.ClassTypeSignature.accept(ClassTypeSignature.java:49) ~[?:1.8.0_51] {}
	at sun.reflect.generics.visitor.Reifier.reifyTypeArguments(Reifier.java:68) ~[?:1.8.0_51] {}
	at sun.reflect.generics.visitor.Reifier.visitClassTypeSignature(Reifier.java:138) ~[?:1.8.0_51] {}
	at sun.reflect.generics.tree.ClassTypeSignature.accept(ClassTypeSignature.java:49) ~[?:1.8.0_51] {}
	at sun.reflect.generics.repository.ClassRepository.getSuperclass(ClassRepository.java:87) ~[?:1.8.0_51] {}
	at java.lang.Class.getGenericSuperclass(Class.java:777) ~[?:1.8.0_51] {}
	at com.google.common.reflect.TypeResolver$TypeMappingIntrospector.visitClass(TypeResolver.java:356) ~[guava-21.0.jar:?] {}
	at com.google.common.reflect.TypeVisitor.visit(TypeVisitor.java:80) ~[guava-21.0.jar:?] {}
	at com.google.common.reflect.TypeResolver$TypeMappingIntrospector.getTypeMappings(TypeResolver.java:350) ~[guava-21.0.jar:?] {}
	at com.google.common.reflect.TypeResolver.accordingTo(TypeResolver.java:64) ~[guava-21.0.jar:?] {}
	at com.google.common.reflect.TypeToken.resolveType(TypeToken.java:249) ~[guava-21.0.jar:?] {}
	at com.google.common.reflect.TypeToken.<init>(TypeToken.java:149) ~[guava-21.0.jar:?] {}
	at net.minecraftforge.registries.ForgeRegistryEntry$1.<init>(ForgeRegistryEntry.java:36) ~[?:?] {re:classloading}
	at net.minecraftforge.registries.ForgeRegistryEntry.<init>(ForgeRegistryEntry.java:36) ~[?:?] {re:computing_frames,re:mixin,re:classloading}
	at net.minecraft.block.AbstractBlock.<init>(AbstractBlock.java:79) ~[?:?] {re:computing_frames,pl:accesstransformer:B,re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B}
	at net.minecraft.block.Block.<init>(Block.java:152) ~[?:?] {re:mixin,pl:accesstransformer:B,re:computing_frames,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:losttrinkets.mixins.json:BlockMixin,pl:mixin:APP:tetrapak.mixins.json:SpawnDropsMixin,pl:mixin:APP:autumnity.mixins.json:BlockMixin,pl:mixin:APP:performant.mixins.json:block.BlockMixin,pl:mixin:APP:performant.mixins.json:forge.BlockMixin,pl:mixin:A}
	at blusunrize.immersiveengineering.common.blocks.IEBaseBlock.<init>(IEBaseBlock.java:65) ~[?:?] {re:classloading}
	at blusunrize.immersiveengineering.common.blocks.IETileProviderBlock.<init>(IETileProviderBlock.java:64) ~[?:?] {re:classloading}
	at blusunrize.immersiveengineering.common.blocks.IEMultiblockBlock.<init>(IEMultiblockBlock.java:35) ~[?:?] {re:classloading}
	at blusunrize.immersiveengineering.common.blocks.metal.MetalMultiblockBlock.<init>(MetalMultiblockBlock.java:27) ~[?:?] {re:classloading}
	at flaxbeard.immersivepetroleum.common.blocks.IPMetalMultiblock.<init>(IPMetalMultiblock.java:20) ~[?:3.3.0-8] {re:classloading}
	at flaxbeard.immersivepetroleum.common.blocks.metal.DistillationTowerBlock.<init>(DistillationTowerBlock.java:20) ~[?:3.3.0-8] {re:classloading}
	at flaxbeard.immersivepetroleum.common.IPContent.populate(IPContent.java:159) ~[?:3.3.0-8] {re:classloading}
	at flaxbeard.immersivepetroleum.ImmersivePetroleum.<init>(ImmersivePetroleum.java:77) ~[?:3.3.0-8] {re:classloading}
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:1.8.0_51] {}
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62) ~[?:1.8.0_51] {}
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:1.8.0_51] {}
	at java.lang.reflect.Constructor.newInstance(Constructor.java:422) ~[?:1.8.0_51] {}
	at java.lang.Class.newInstance(Class.java:442) ~[?:1.8.0_51] {}
	at net.minecraftforge.fml.javafmlmod.FMLModContainer.constructMod(FMLModContainer.java:81) ~[?:36.2] {re:classloading}
	at net.minecraftforge.fml.javafmlmod.FMLModContainer$$Lambda$3201/614662563.run(Unknown Source) ~[?:?] {}
	at net.minecraftforge.fml.ModContainer.lambda$buildTransitionHandler$4(ModContainer.java:120) ~[?:?] {re:classloading}
	at net.minecraftforge.fml.ModContainer$$Lambda$3696/1606749232.run(Unknown Source) ~[?:?] {}
	at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1618) ~[?:1.8.0_51] {}
	at java.util.concurrent.CompletableFuture$AsyncRun.exec(CompletableFuture.java:1610) ~[?:1.8.0_51] {}
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289) ~[?:1.8.0_51] {}
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056) ~[?:1.8.0_51] {}
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1689) ~[?:1.8.0_51] {re:computing_frames}
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157) ~[?:1.8.0_51] {}
```

### Screenshot(s)
Images say more than a thousand words, so if you are bad at explaining things like me, throw in some images to accompany the `What happend?` section above.  
(Perhaps you could even reference them in that section too)

**Comment by TwistedGate** [comment]
#69
